//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.ProductsSampleData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class ProductsSampleData { }
#else

	public class ProductsSampleData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public ProductsSampleData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/ControlTemplates;component/SampleData/ProductsSampleData/ProductsSampleData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Products _Products = new Products();

		public Products Products
		{
			get
			{
				return this._Products;
			}
		}
	}

	public class ProductsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Description = string.Empty;

		public string Description
		{
			get
			{
				return this._Description;
			}

			set
			{
				if (this._Description != value)
				{
					this._Description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}

		private System.Windows.Media.ImageSource _ProductImage = null;

		public System.Windows.Media.ImageSource ProductImage
		{
			get
			{
				return this._ProductImage;
			}

			set
			{
				if (this._ProductImage != value)
				{
					this._ProductImage = value;
					this.OnPropertyChanged("ProductImage");
				}
			}
		}

		private string _Url = string.Empty;

		public string Url
		{
			get
			{
				return this._Url;
			}

			set
			{
				if (this._Url != value)
				{
					this._Url = value;
					this.OnPropertyChanged("Url");
				}
			}
		}

		private string _Price = string.Empty;

		public string Price
		{
			get
			{
				return this._Price;
			}

			set
			{
				if (this._Price != value)
				{
					this._Price = value;
					this.OnPropertyChanged("Price");
				}
			}
		}
	}

	public class Products : System.Collections.ObjectModel.ObservableCollection<ProductsItem>
	{ 
	}
#endif
}
