//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by slsvcutil, version 3.0.40818.0
// 
namespace WcfRemoteServices.model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class Product : System.Data.Objects.DataClasses.EntityObject
    {
        
        private string ClassField;
        
        private string ColorField;
        
        private int DaysToManufactureField;
        
        private System.Nullable<System.DateTime> DiscontinuedDateField;
        
        private bool FinishedGoodsFlagField;
        
        private decimal ListPriceField;
        
        private bool MakeFlagField;
        
        private System.DateTime ModifiedDateField;
        
        private string NameField;
        
        private int ProductIDField;
        
        private WcfRemoteServices.model.ProductInventory[] ProductInventoriesField;
        
        private string ProductLineField;
        
        private System.Nullable<int> ProductModelIDField;
        
        private string ProductNumberField;
        
        private WcfRemoteServices.model.ProductSubcategory ProductSubcategoryField;
        
        private System.Nullable<int> ProductSubcategoryIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfProductSubcategoryumD5WrpY ProductSubcategoryReferenceField;
        
        private short ReorderPointField;
        
        private short SafetyStockLevelField;
        
        private System.Nullable<System.DateTime> SellEndDateField;
        
        private System.DateTime SellStartDateField;
        
        private string SizeField;
        
        private string SizeUnitMeasureCodeField;
        
        private decimal StandardCostField;
        
        private string StyleField;
        
        private System.Nullable<decimal> WeightField;
        
        private string WeightUnitMeasureCodeField;
        
        private System.Guid rowguidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DaysToManufacture
        {
            get
            {
                return this.DaysToManufactureField;
            }
            set
            {
                this.DaysToManufactureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DiscontinuedDate
        {
            get
            {
                return this.DiscontinuedDateField;
            }
            set
            {
                this.DiscontinuedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FinishedGoodsFlag
        {
            get
            {
                return this.FinishedGoodsFlagField;
            }
            set
            {
                this.FinishedGoodsFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ListPrice
        {
            get
            {
                return this.ListPriceField;
            }
            set
            {
                this.ListPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MakeFlag
        {
            get
            {
                return this.MakeFlagField;
            }
            set
            {
                this.MakeFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.ProductInventory[] ProductInventories
        {
            get
            {
                return this.ProductInventoriesField;
            }
            set
            {
                this.ProductInventoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductLine
        {
            get
            {
                return this.ProductLineField;
            }
            set
            {
                this.ProductLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductModelID
        {
            get
            {
                return this.ProductModelIDField;
            }
            set
            {
                this.ProductModelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber
        {
            get
            {
                return this.ProductNumberField;
            }
            set
            {
                this.ProductNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.ProductSubcategory ProductSubcategory
        {
            get
            {
                return this.ProductSubcategoryField;
            }
            set
            {
                this.ProductSubcategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductSubcategoryID
        {
            get
            {
                return this.ProductSubcategoryIDField;
            }
            set
            {
                this.ProductSubcategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfProductSubcategoryumD5WrpY ProductSubcategoryReference
        {
            get
            {
                return this.ProductSubcategoryReferenceField;
            }
            set
            {
                this.ProductSubcategoryReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ReorderPoint
        {
            get
            {
                return this.ReorderPointField;
            }
            set
            {
                this.ReorderPointField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SafetyStockLevel
        {
            get
            {
                return this.SafetyStockLevelField;
            }
            set
            {
                this.SafetyStockLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SellEndDate
        {
            get
            {
                return this.SellEndDateField;
            }
            set
            {
                this.SellEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SellStartDate
        {
            get
            {
                return this.SellStartDateField;
            }
            set
            {
                this.SellStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SizeUnitMeasureCode
        {
            get
            {
                return this.SizeUnitMeasureCodeField;
            }
            set
            {
                this.SizeUnitMeasureCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StandardCost
        {
            get
            {
                return this.StandardCostField;
            }
            set
            {
                this.StandardCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style
        {
            get
            {
                return this.StyleField;
            }
            set
            {
                this.StyleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WeightUnitMeasureCode
        {
            get
            {
                return this.WeightUnitMeasureCodeField;
            }
            set
            {
                this.WeightUnitMeasureCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid
        {
            get
            {
                return this.rowguidField;
            }
            set
            {
                this.rowguidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInventory", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class ProductInventory : System.Data.Objects.DataClasses.EntityObject
    {
        
        private byte BinField;
        
        private short LocationIDField;
        
        private System.DateTime ModifiedDateField;
        
        private WcfRemoteServices.model.Product ProductField;
        
        private int ProductIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfProductumD5WrpY ProductReferenceField;
        
        private short QuantityField;
        
        private string ShelfField;
        
        private System.Guid rowguidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Bin
        {
            get
            {
                return this.BinField;
            }
            set
            {
                this.BinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                this.LocationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this.ProductIDField;
            }
            set
            {
                this.ProductIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfProductumD5WrpY ProductReference
        {
            get
            {
                return this.ProductReferenceField;
            }
            set
            {
                this.ProductReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shelf
        {
            get
            {
                return this.ShelfField;
            }
            set
            {
                this.ShelfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid
        {
            get
            {
                return this.rowguidField;
            }
            set
            {
                this.rowguidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSubcategory", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class ProductSubcategory : System.Data.Objects.DataClasses.EntityObject
    {
        
        private System.DateTime ModifiedDateField;
        
        private string NameField;
        
        private WcfRemoteServices.model.ProductCategory ProductCategoryField;
        
        private int ProductCategoryIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfProductCategoryumD5WrpY ProductCategoryReferenceField;
        
        private int ProductSubcategoryIDField;
        
        private WcfRemoteServices.model.Product[] ProductsField;
        
        private System.Guid rowguidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.ProductCategory ProductCategory
        {
            get
            {
                return this.ProductCategoryField;
            }
            set
            {
                this.ProductCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryID
        {
            get
            {
                return this.ProductCategoryIDField;
            }
            set
            {
                this.ProductCategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfProductCategoryumD5WrpY ProductCategoryReference
        {
            get
            {
                return this.ProductCategoryReferenceField;
            }
            set
            {
                this.ProductCategoryReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductSubcategoryID
        {
            get
            {
                return this.ProductSubcategoryIDField;
            }
            set
            {
                this.ProductSubcategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.Product[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid
        {
            get
            {
                return this.rowguidField;
            }
            set
            {
                this.rowguidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategory", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class ProductCategory : System.Data.Objects.DataClasses.EntityObject
    {
        
        private System.DateTime ModifiedDateField;
        
        private string NameField;
        
        private int ProductCategoryIDField;
        
        private WcfRemoteServices.model.ProductSubcategory[] ProductSubcategoriesField;
        
        private System.Guid rowguidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryID
        {
            get
            {
                return this.ProductCategoryIDField;
            }
            set
            {
                this.ProductCategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.ProductSubcategory[] ProductSubcategories
        {
            get
            {
                return this.ProductSubcategoriesField;
            }
            set
            {
                this.ProductSubcategoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid
        {
            get
            {
                return this.rowguidField;
            }
            set
            {
                this.rowguidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vendor", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class Vendor : System.Data.Objects.DataClasses.EntityObject
    {
        
        private string AccountNumberField;
        
        private bool ActiveFlagField;
        
        private byte CreditRatingField;
        
        private System.DateTime ModifiedDateField;
        
        private string NameField;
        
        private bool PreferredVendorStatusField;
        
        private string PurchasingWebServiceURLField;
        
        private WcfRemoteServices.model.VendorAddress[] VendorAddressesField;
        
        private WcfRemoteServices.model.VendorContact[] VendorContactsField;
        
        private int VendorIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActiveFlag
        {
            get
            {
                return this.ActiveFlagField;
            }
            set
            {
                this.ActiveFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CreditRating
        {
            get
            {
                return this.CreditRatingField;
            }
            set
            {
                this.CreditRatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PreferredVendorStatus
        {
            get
            {
                return this.PreferredVendorStatusField;
            }
            set
            {
                this.PreferredVendorStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchasingWebServiceURL
        {
            get
            {
                return this.PurchasingWebServiceURLField;
            }
            set
            {
                this.PurchasingWebServiceURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.VendorAddress[] VendorAddresses
        {
            get
            {
                return this.VendorAddressesField;
            }
            set
            {
                this.VendorAddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.VendorContact[] VendorContacts
        {
            get
            {
                return this.VendorContactsField;
            }
            set
            {
                this.VendorContactsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VendorID
        {
            get
            {
                return this.VendorIDField;
            }
            set
            {
                this.VendorIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendorAddress", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class VendorAddress : System.Data.Objects.DataClasses.EntityObject
    {
        
        private WcfRemoteServices.model.Address AddressField;
        
        private int AddressIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfAddressumD5WrpY AddressReferenceField;
        
        private WcfRemoteServices.model.AddressType AddressTypeField;
        
        private int AddressTypeIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfAddressTypeumD5WrpY AddressTypeReferenceField;
        
        private System.DateTime ModifiedDateField;
        
        private WcfRemoteServices.model.Vendor VendorField;
        
        private int VendorIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfVendorumD5WrpY VendorReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.Address Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID
        {
            get
            {
                return this.AddressIDField;
            }
            set
            {
                this.AddressIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfAddressumD5WrpY AddressReference
        {
            get
            {
                return this.AddressReferenceField;
            }
            set
            {
                this.AddressReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.AddressType AddressType
        {
            get
            {
                return this.AddressTypeField;
            }
            set
            {
                this.AddressTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressTypeID
        {
            get
            {
                return this.AddressTypeIDField;
            }
            set
            {
                this.AddressTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfAddressTypeumD5WrpY AddressTypeReference
        {
            get
            {
                return this.AddressTypeReferenceField;
            }
            set
            {
                this.AddressTypeReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.Vendor Vendor
        {
            get
            {
                return this.VendorField;
            }
            set
            {
                this.VendorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VendorID
        {
            get
            {
                return this.VendorIDField;
            }
            set
            {
                this.VendorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfVendorumD5WrpY VendorReference
        {
            get
            {
                return this.VendorReferenceField;
            }
            set
            {
                this.VendorReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class Address : System.Data.Objects.DataClasses.EntityObject
    {
        
        private int AddressIDField;
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string CityField;
        
        private System.DateTime ModifiedDateField;
        
        private string PostalCodeField;
        
        private int StateProvinceIDField;
        
        private WcfRemoteServices.model.VendorAddress[] VendorAddressesField;
        
        private System.Guid rowguidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID
        {
            get
            {
                return this.AddressIDField;
            }
            set
            {
                this.AddressIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateProvinceID
        {
            get
            {
                return this.StateProvinceIDField;
            }
            set
            {
                this.StateProvinceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.VendorAddress[] VendorAddresses
        {
            get
            {
                return this.VendorAddressesField;
            }
            set
            {
                this.VendorAddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid
        {
            get
            {
                return this.rowguidField;
            }
            set
            {
                this.rowguidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class AddressType : System.Data.Objects.DataClasses.EntityObject
    {
        
        private int AddressTypeIDField;
        
        private System.DateTime ModifiedDateField;
        
        private string NameField;
        
        private WcfRemoteServices.model.VendorAddress[] VendorAddressesField;
        
        private System.Guid rowguidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressTypeID
        {
            get
            {
                return this.AddressTypeIDField;
            }
            set
            {
                this.AddressTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.VendorAddress[] VendorAddresses
        {
            get
            {
                return this.VendorAddressesField;
            }
            set
            {
                this.VendorAddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid
        {
            get
            {
                return this.rowguidField;
            }
            set
            {
                this.rowguidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendorContact", Namespace="http://schemas.datacontract.org/2004/07/WcfRemoteServices.model", IsReference=true)]
    public partial class VendorContact : System.Data.Objects.DataClasses.EntityObject
    {
        
        private int ContactIDField;
        
        private int ContactTypeIDField;
        
        private System.DateTime ModifiedDateField;
        
        private WcfRemoteServices.model.Vendor VendorField;
        
        private int VendorIDField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfVendorumD5WrpY VendorReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactID
        {
            get
            {
                return this.ContactIDField;
            }
            set
            {
                this.ContactIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactTypeID
        {
            get
            {
                return this.ContactTypeIDField;
            }
            set
            {
                this.ContactTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfRemoteServices.model.Vendor Vendor
        {
            get
            {
                return this.VendorField;
            }
            set
            {
                this.VendorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VendorID
        {
            get
            {
                return this.VendorIDField;
            }
            set
            {
                this.VendorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfVendorumD5WrpY VendorReference
        {
            get
            {
                return this.VendorReferenceField;
            }
            set
            {
                this.VendorReferenceField = value;
            }
        }
    }
}
namespace System.Data.Objects.DataClasses
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductInventory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductSubcategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Vendor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.VendorAddress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Address))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.AddressType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.VendorContact))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Product))]
    public partial class StructuralObject : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductInventory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductSubcategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Vendor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.VendorAddress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Address))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.AddressType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.VendorContact))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Product))]
    public partial class EntityObject : System.Data.Objects.DataClasses.StructuralObject
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfProductSubcategoryumD5WrpY", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfProductSubcategoryumD5WrpY : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfProductumD5WrpY", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfProductumD5WrpY : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductCategoryumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductSubcategoryumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfAddressumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfAddressTypeumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfVendorumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductumD5WrpY))]
    public partial class EntityReference : System.Data.Objects.DataClasses.RelatedEnd
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductCategoryumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductSubcategoryumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfAddressumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfAddressTypeumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfVendorumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductumD5WrpY))]
    public partial class RelatedEnd : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfProductCategoryumD5WrpY", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfProductCategoryumD5WrpY : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfAddressumD5WrpY", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfAddressumD5WrpY : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfAddressTypeumD5WrpY", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfAddressTypeumD5WrpY : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfVendorumD5WrpY", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfVendorumD5WrpY : System.Data.Objects.DataClasses.EntityReference
    {
    }
}
namespace System.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object
    {
        
        private string EntityContainerNameField;
        
        private System.Data.EntityKeyMember[] EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName
        {
            get
            {
                return this.EntityContainerNameField;
            }
            set
            {
                this.EntityContainerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKeyMember[] EntityKeyValues
        {
            get
            {
                return this.EntityKeyValuesField;
            }
            set
            {
                this.EntityKeyValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName
        {
            get
            {
                return this.EntitySetNameField;
            }
            set
            {
                this.EntitySetNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Product[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductInventory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductInventory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductSubcategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductSubcategory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.ProductCategory[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Vendor[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Vendor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.VendorAddress[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.VendorAddress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.Address))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.AddressType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.VendorContact[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfRemoteServices.model.VendorContact))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductCategoryumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfProductSubcategoryumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfAddressumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfAddressTypeumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfVendorumD5WrpY))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember[]))]
    public partial class EntityKeyMember : object
    {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAdventureWorks")]
public interface IAdventureWorks
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAdventureWorks/FullProductList", ReplyAction="http://tempuri.org/IAdventureWorks/FullProductListResponse")]
    System.IAsyncResult BeginFullProductList(System.AsyncCallback callback, object asyncState);
    
    WcfRemoteServices.model.Product[] EndFullProductList(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAdventureWorks/ProductCategoryList", ReplyAction="http://tempuri.org/IAdventureWorks/ProductCategoryListResponse")]
    System.IAsyncResult BeginProductCategoryList(System.AsyncCallback callback, object asyncState);
    
    WcfRemoteServices.model.ProductCategory[] EndProductCategoryList(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAdventureWorks/ProductSubcategoryList", ReplyAction="http://tempuri.org/IAdventureWorks/ProductSubcategoryListResponse")]
    System.IAsyncResult BeginProductSubcategoryList(System.AsyncCallback callback, object asyncState);
    
    WcfRemoteServices.model.ProductSubcategory[] EndProductSubcategoryList(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAdventureWorks/GetProductsByCategory", ReplyAction="http://tempuri.org/IAdventureWorks/GetProductsByCategoryResponse")]
    System.IAsyncResult BeginGetProductsByCategory(int CategoryID, System.AsyncCallback callback, object asyncState);
    
    WcfRemoteServices.model.Product[] EndGetProductsByCategory(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAdventureWorks/GetProductsBySubcategory", ReplyAction="http://tempuri.org/IAdventureWorks/GetProductsBySubcategoryResponse")]
    System.IAsyncResult BeginGetProductsBySubcategory(int SubCategoryID, System.AsyncCallback callback, object asyncState);
    
    WcfRemoteServices.model.Product[] EndGetProductsBySubcategory(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAdventureWorks/CheckInventory", ReplyAction="http://tempuri.org/IAdventureWorks/CheckInventoryResponse")]
    System.IAsyncResult BeginCheckInventory(int ProductID, System.AsyncCallback callback, object asyncState);
    
    int EndCheckInventory(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAdventureWorks/FullVendorList", ReplyAction="http://tempuri.org/IAdventureWorks/FullVendorListResponse")]
    System.IAsyncResult BeginFullVendorList(System.AsyncCallback callback, object asyncState);
    
    WcfRemoteServices.model.Vendor[] EndFullVendorList(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IAdventureWorksChannel : IAdventureWorks, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class FullProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public FullProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfRemoteServices.model.Product[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfRemoteServices.model.Product[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ProductCategoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ProductCategoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfRemoteServices.model.ProductCategory[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfRemoteServices.model.ProductCategory[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ProductSubcategoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ProductSubcategoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfRemoteServices.model.ProductSubcategory[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfRemoteServices.model.ProductSubcategory[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetProductsByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetProductsByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfRemoteServices.model.Product[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfRemoteServices.model.Product[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetProductsBySubcategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetProductsBySubcategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfRemoteServices.model.Product[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfRemoteServices.model.Product[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CheckInventoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public CheckInventoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public int Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class FullVendorListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public FullVendorListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfRemoteServices.model.Vendor[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfRemoteServices.model.Vendor[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class AdventureWorksClient : System.ServiceModel.ClientBase<IAdventureWorks>, IAdventureWorks
{
    
    private BeginOperationDelegate onBeginFullProductListDelegate;
    
    private EndOperationDelegate onEndFullProductListDelegate;
    
    private System.Threading.SendOrPostCallback onFullProductListCompletedDelegate;
    
    private BeginOperationDelegate onBeginProductCategoryListDelegate;
    
    private EndOperationDelegate onEndProductCategoryListDelegate;
    
    private System.Threading.SendOrPostCallback onProductCategoryListCompletedDelegate;
    
    private BeginOperationDelegate onBeginProductSubcategoryListDelegate;
    
    private EndOperationDelegate onEndProductSubcategoryListDelegate;
    
    private System.Threading.SendOrPostCallback onProductSubcategoryListCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetProductsByCategoryDelegate;
    
    private EndOperationDelegate onEndGetProductsByCategoryDelegate;
    
    private System.Threading.SendOrPostCallback onGetProductsByCategoryCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetProductsBySubcategoryDelegate;
    
    private EndOperationDelegate onEndGetProductsBySubcategoryDelegate;
    
    private System.Threading.SendOrPostCallback onGetProductsBySubcategoryCompletedDelegate;
    
    private BeginOperationDelegate onBeginCheckInventoryDelegate;
    
    private EndOperationDelegate onEndCheckInventoryDelegate;
    
    private System.Threading.SendOrPostCallback onCheckInventoryCompletedDelegate;
    
    private BeginOperationDelegate onBeginFullVendorListDelegate;
    
    private EndOperationDelegate onEndFullVendorListDelegate;
    
    private System.Threading.SendOrPostCallback onFullVendorListCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public AdventureWorksClient()
    {
    }
    
    public AdventureWorksClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AdventureWorksClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AdventureWorksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AdventureWorksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<FullProductListCompletedEventArgs> FullProductListCompleted;
    
    public event System.EventHandler<ProductCategoryListCompletedEventArgs> ProductCategoryListCompleted;
    
    public event System.EventHandler<ProductSubcategoryListCompletedEventArgs> ProductSubcategoryListCompleted;
    
    public event System.EventHandler<GetProductsByCategoryCompletedEventArgs> GetProductsByCategoryCompleted;
    
    public event System.EventHandler<GetProductsBySubcategoryCompletedEventArgs> GetProductsBySubcategoryCompleted;
    
    public event System.EventHandler<CheckInventoryCompletedEventArgs> CheckInventoryCompleted;
    
    public event System.EventHandler<FullVendorListCompletedEventArgs> FullVendorListCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAdventureWorks.BeginFullProductList(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginFullProductList(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfRemoteServices.model.Product[] IAdventureWorks.EndFullProductList(System.IAsyncResult result)
    {
        return base.Channel.EndFullProductList(result);
    }
    
    private System.IAsyncResult OnBeginFullProductList(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IAdventureWorks)(this)).BeginFullProductList(callback, asyncState);
    }
    
    private object[] OnEndFullProductList(System.IAsyncResult result)
    {
        WcfRemoteServices.model.Product[] retVal = ((IAdventureWorks)(this)).EndFullProductList(result);
        return new object[] {
                retVal};
    }
    
    private void OnFullProductListCompleted(object state)
    {
        if ((this.FullProductListCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.FullProductListCompleted(this, new FullProductListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void FullProductListAsync()
    {
        this.FullProductListAsync(null);
    }
    
    public void FullProductListAsync(object userState)
    {
        if ((this.onBeginFullProductListDelegate == null))
        {
            this.onBeginFullProductListDelegate = new BeginOperationDelegate(this.OnBeginFullProductList);
        }
        if ((this.onEndFullProductListDelegate == null))
        {
            this.onEndFullProductListDelegate = new EndOperationDelegate(this.OnEndFullProductList);
        }
        if ((this.onFullProductListCompletedDelegate == null))
        {
            this.onFullProductListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFullProductListCompleted);
        }
        base.InvokeAsync(this.onBeginFullProductListDelegate, null, this.onEndFullProductListDelegate, this.onFullProductListCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAdventureWorks.BeginProductCategoryList(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginProductCategoryList(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfRemoteServices.model.ProductCategory[] IAdventureWorks.EndProductCategoryList(System.IAsyncResult result)
    {
        return base.Channel.EndProductCategoryList(result);
    }
    
    private System.IAsyncResult OnBeginProductCategoryList(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IAdventureWorks)(this)).BeginProductCategoryList(callback, asyncState);
    }
    
    private object[] OnEndProductCategoryList(System.IAsyncResult result)
    {
        WcfRemoteServices.model.ProductCategory[] retVal = ((IAdventureWorks)(this)).EndProductCategoryList(result);
        return new object[] {
                retVal};
    }
    
    private void OnProductCategoryListCompleted(object state)
    {
        if ((this.ProductCategoryListCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ProductCategoryListCompleted(this, new ProductCategoryListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ProductCategoryListAsync()
    {
        this.ProductCategoryListAsync(null);
    }
    
    public void ProductCategoryListAsync(object userState)
    {
        if ((this.onBeginProductCategoryListDelegate == null))
        {
            this.onBeginProductCategoryListDelegate = new BeginOperationDelegate(this.OnBeginProductCategoryList);
        }
        if ((this.onEndProductCategoryListDelegate == null))
        {
            this.onEndProductCategoryListDelegate = new EndOperationDelegate(this.OnEndProductCategoryList);
        }
        if ((this.onProductCategoryListCompletedDelegate == null))
        {
            this.onProductCategoryListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProductCategoryListCompleted);
        }
        base.InvokeAsync(this.onBeginProductCategoryListDelegate, null, this.onEndProductCategoryListDelegate, this.onProductCategoryListCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAdventureWorks.BeginProductSubcategoryList(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginProductSubcategoryList(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfRemoteServices.model.ProductSubcategory[] IAdventureWorks.EndProductSubcategoryList(System.IAsyncResult result)
    {
        return base.Channel.EndProductSubcategoryList(result);
    }
    
    private System.IAsyncResult OnBeginProductSubcategoryList(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IAdventureWorks)(this)).BeginProductSubcategoryList(callback, asyncState);
    }
    
    private object[] OnEndProductSubcategoryList(System.IAsyncResult result)
    {
        WcfRemoteServices.model.ProductSubcategory[] retVal = ((IAdventureWorks)(this)).EndProductSubcategoryList(result);
        return new object[] {
                retVal};
    }
    
    private void OnProductSubcategoryListCompleted(object state)
    {
        if ((this.ProductSubcategoryListCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ProductSubcategoryListCompleted(this, new ProductSubcategoryListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ProductSubcategoryListAsync()
    {
        this.ProductSubcategoryListAsync(null);
    }
    
    public void ProductSubcategoryListAsync(object userState)
    {
        if ((this.onBeginProductSubcategoryListDelegate == null))
        {
            this.onBeginProductSubcategoryListDelegate = new BeginOperationDelegate(this.OnBeginProductSubcategoryList);
        }
        if ((this.onEndProductSubcategoryListDelegate == null))
        {
            this.onEndProductSubcategoryListDelegate = new EndOperationDelegate(this.OnEndProductSubcategoryList);
        }
        if ((this.onProductSubcategoryListCompletedDelegate == null))
        {
            this.onProductSubcategoryListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProductSubcategoryListCompleted);
        }
        base.InvokeAsync(this.onBeginProductSubcategoryListDelegate, null, this.onEndProductSubcategoryListDelegate, this.onProductSubcategoryListCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAdventureWorks.BeginGetProductsByCategory(int CategoryID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetProductsByCategory(CategoryID, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfRemoteServices.model.Product[] IAdventureWorks.EndGetProductsByCategory(System.IAsyncResult result)
    {
        return base.Channel.EndGetProductsByCategory(result);
    }
    
    private System.IAsyncResult OnBeginGetProductsByCategory(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int CategoryID = ((int)(inValues[0]));
        return ((IAdventureWorks)(this)).BeginGetProductsByCategory(CategoryID, callback, asyncState);
    }
    
    private object[] OnEndGetProductsByCategory(System.IAsyncResult result)
    {
        WcfRemoteServices.model.Product[] retVal = ((IAdventureWorks)(this)).EndGetProductsByCategory(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetProductsByCategoryCompleted(object state)
    {
        if ((this.GetProductsByCategoryCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetProductsByCategoryCompleted(this, new GetProductsByCategoryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetProductsByCategoryAsync(int CategoryID)
    {
        this.GetProductsByCategoryAsync(CategoryID, null);
    }
    
    public void GetProductsByCategoryAsync(int CategoryID, object userState)
    {
        if ((this.onBeginGetProductsByCategoryDelegate == null))
        {
            this.onBeginGetProductsByCategoryDelegate = new BeginOperationDelegate(this.OnBeginGetProductsByCategory);
        }
        if ((this.onEndGetProductsByCategoryDelegate == null))
        {
            this.onEndGetProductsByCategoryDelegate = new EndOperationDelegate(this.OnEndGetProductsByCategory);
        }
        if ((this.onGetProductsByCategoryCompletedDelegate == null))
        {
            this.onGetProductsByCategoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductsByCategoryCompleted);
        }
        base.InvokeAsync(this.onBeginGetProductsByCategoryDelegate, new object[] {
                    CategoryID}, this.onEndGetProductsByCategoryDelegate, this.onGetProductsByCategoryCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAdventureWorks.BeginGetProductsBySubcategory(int SubCategoryID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetProductsBySubcategory(SubCategoryID, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfRemoteServices.model.Product[] IAdventureWorks.EndGetProductsBySubcategory(System.IAsyncResult result)
    {
        return base.Channel.EndGetProductsBySubcategory(result);
    }
    
    private System.IAsyncResult OnBeginGetProductsBySubcategory(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int SubCategoryID = ((int)(inValues[0]));
        return ((IAdventureWorks)(this)).BeginGetProductsBySubcategory(SubCategoryID, callback, asyncState);
    }
    
    private object[] OnEndGetProductsBySubcategory(System.IAsyncResult result)
    {
        WcfRemoteServices.model.Product[] retVal = ((IAdventureWorks)(this)).EndGetProductsBySubcategory(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetProductsBySubcategoryCompleted(object state)
    {
        if ((this.GetProductsBySubcategoryCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetProductsBySubcategoryCompleted(this, new GetProductsBySubcategoryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetProductsBySubcategoryAsync(int SubCategoryID)
    {
        this.GetProductsBySubcategoryAsync(SubCategoryID, null);
    }
    
    public void GetProductsBySubcategoryAsync(int SubCategoryID, object userState)
    {
        if ((this.onBeginGetProductsBySubcategoryDelegate == null))
        {
            this.onBeginGetProductsBySubcategoryDelegate = new BeginOperationDelegate(this.OnBeginGetProductsBySubcategory);
        }
        if ((this.onEndGetProductsBySubcategoryDelegate == null))
        {
            this.onEndGetProductsBySubcategoryDelegate = new EndOperationDelegate(this.OnEndGetProductsBySubcategory);
        }
        if ((this.onGetProductsBySubcategoryCompletedDelegate == null))
        {
            this.onGetProductsBySubcategoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductsBySubcategoryCompleted);
        }
        base.InvokeAsync(this.onBeginGetProductsBySubcategoryDelegate, new object[] {
                    SubCategoryID}, this.onEndGetProductsBySubcategoryDelegate, this.onGetProductsBySubcategoryCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAdventureWorks.BeginCheckInventory(int ProductID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginCheckInventory(ProductID, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    int IAdventureWorks.EndCheckInventory(System.IAsyncResult result)
    {
        return base.Channel.EndCheckInventory(result);
    }
    
    private System.IAsyncResult OnBeginCheckInventory(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int ProductID = ((int)(inValues[0]));
        return ((IAdventureWorks)(this)).BeginCheckInventory(ProductID, callback, asyncState);
    }
    
    private object[] OnEndCheckInventory(System.IAsyncResult result)
    {
        int retVal = ((IAdventureWorks)(this)).EndCheckInventory(result);
        return new object[] {
                retVal};
    }
    
    private void OnCheckInventoryCompleted(object state)
    {
        if ((this.CheckInventoryCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CheckInventoryCompleted(this, new CheckInventoryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CheckInventoryAsync(int ProductID)
    {
        this.CheckInventoryAsync(ProductID, null);
    }
    
    public void CheckInventoryAsync(int ProductID, object userState)
    {
        if ((this.onBeginCheckInventoryDelegate == null))
        {
            this.onBeginCheckInventoryDelegate = new BeginOperationDelegate(this.OnBeginCheckInventory);
        }
        if ((this.onEndCheckInventoryDelegate == null))
        {
            this.onEndCheckInventoryDelegate = new EndOperationDelegate(this.OnEndCheckInventory);
        }
        if ((this.onCheckInventoryCompletedDelegate == null))
        {
            this.onCheckInventoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckInventoryCompleted);
        }
        base.InvokeAsync(this.onBeginCheckInventoryDelegate, new object[] {
                    ProductID}, this.onEndCheckInventoryDelegate, this.onCheckInventoryCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAdventureWorks.BeginFullVendorList(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginFullVendorList(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfRemoteServices.model.Vendor[] IAdventureWorks.EndFullVendorList(System.IAsyncResult result)
    {
        return base.Channel.EndFullVendorList(result);
    }
    
    private System.IAsyncResult OnBeginFullVendorList(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IAdventureWorks)(this)).BeginFullVendorList(callback, asyncState);
    }
    
    private object[] OnEndFullVendorList(System.IAsyncResult result)
    {
        WcfRemoteServices.model.Vendor[] retVal = ((IAdventureWorks)(this)).EndFullVendorList(result);
        return new object[] {
                retVal};
    }
    
    private void OnFullVendorListCompleted(object state)
    {
        if ((this.FullVendorListCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.FullVendorListCompleted(this, new FullVendorListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void FullVendorListAsync()
    {
        this.FullVendorListAsync(null);
    }
    
    public void FullVendorListAsync(object userState)
    {
        if ((this.onBeginFullVendorListDelegate == null))
        {
            this.onBeginFullVendorListDelegate = new BeginOperationDelegate(this.OnBeginFullVendorList);
        }
        if ((this.onEndFullVendorListDelegate == null))
        {
            this.onEndFullVendorListDelegate = new EndOperationDelegate(this.OnEndFullVendorList);
        }
        if ((this.onFullVendorListCompletedDelegate == null))
        {
            this.onFullVendorListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFullVendorListCompleted);
        }
        base.InvokeAsync(this.onBeginFullVendorListDelegate, null, this.onEndFullVendorListDelegate, this.onFullVendorListCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IAdventureWorks CreateChannel()
    {
        return new AdventureWorksClientChannel(this);
    }
    
    private class AdventureWorksClientChannel : ChannelBase<IAdventureWorks>, IAdventureWorks
    {
        
        public AdventureWorksClientChannel(System.ServiceModel.ClientBase<IAdventureWorks> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginFullProductList(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("FullProductList", _args, callback, asyncState);
            return _result;
        }
        
        public WcfRemoteServices.model.Product[] EndFullProductList(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfRemoteServices.model.Product[] _result = ((WcfRemoteServices.model.Product[])(base.EndInvoke("FullProductList", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginProductCategoryList(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("ProductCategoryList", _args, callback, asyncState);
            return _result;
        }
        
        public WcfRemoteServices.model.ProductCategory[] EndProductCategoryList(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfRemoteServices.model.ProductCategory[] _result = ((WcfRemoteServices.model.ProductCategory[])(base.EndInvoke("ProductCategoryList", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginProductSubcategoryList(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("ProductSubcategoryList", _args, callback, asyncState);
            return _result;
        }
        
        public WcfRemoteServices.model.ProductSubcategory[] EndProductSubcategoryList(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfRemoteServices.model.ProductSubcategory[] _result = ((WcfRemoteServices.model.ProductSubcategory[])(base.EndInvoke("ProductSubcategoryList", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetProductsByCategory(int CategoryID, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = CategoryID;
            System.IAsyncResult _result = base.BeginInvoke("GetProductsByCategory", _args, callback, asyncState);
            return _result;
        }
        
        public WcfRemoteServices.model.Product[] EndGetProductsByCategory(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfRemoteServices.model.Product[] _result = ((WcfRemoteServices.model.Product[])(base.EndInvoke("GetProductsByCategory", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetProductsBySubcategory(int SubCategoryID, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = SubCategoryID;
            System.IAsyncResult _result = base.BeginInvoke("GetProductsBySubcategory", _args, callback, asyncState);
            return _result;
        }
        
        public WcfRemoteServices.model.Product[] EndGetProductsBySubcategory(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfRemoteServices.model.Product[] _result = ((WcfRemoteServices.model.Product[])(base.EndInvoke("GetProductsBySubcategory", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginCheckInventory(int ProductID, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = ProductID;
            System.IAsyncResult _result = base.BeginInvoke("CheckInventory", _args, callback, asyncState);
            return _result;
        }
        
        public int EndCheckInventory(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            int _result = ((int)(base.EndInvoke("CheckInventory", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginFullVendorList(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("FullVendorList", _args, callback, asyncState);
            return _result;
        }
        
        public WcfRemoteServices.model.Vendor[] EndFullVendorList(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfRemoteServices.model.Vendor[] _result = ((WcfRemoteServices.model.Vendor[])(base.EndInvoke("FullVendorList", _args, result)));
            return _result;
        }
    }
}
